FROM node AS builder

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

COPY --chown=node:node client/package.json client/yarn.lock ./

USER node

RUN yarn install

COPY --chown=node:node client/ .

RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]