FROM node


RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

COPY --chown=node:node client/package.json client/yarn.lock ./

USER node

RUN yarn install

COPY --chown=node:node client/ .

EXPOSE 5173

CMD ["yarn", "dev"]